"""FunctorFlow v3 public API."""

from typing import TYPE_CHECKING

from .agentic_workflows import (
    AgentNode,
    AgentSpec,
    AgenticWorkflow,
    ArtifactNode,
    ArtifactSpec,
    AttentionColimit,
    AttentionSpec,
    DiffusionLimit,
    DiffusionSpec,
    build_agentic_workflow,
)
from .blueprints import build_basket_rocket_workflow, build_democritus_workflow
from .consciousness import (
    AttentionScoreWeights,
    BroadcastSelection,
    ConsciousBroadcast,
    ConsciousBroadcastBoard,
    ConsciousFieldOfView,
    ConsciousWorkspaceState,
    ConsciousnessFunctor,
    UnconsciousProcess,
)
from .csql_bundle import BatchCSQLBundleResult
from .semantic_kernel import Category, Functor, Interface, ModelObject, Morphism

if TYPE_CHECKING:
    from .basket_rocket_sec_agentic import (
        BasketRocketBatchAgenticRunner,
        BasketRocketBatchRecord,
        BasketRocketBatchRunResult,
        BasketRocketSECAgenticConfig,
        BasketRocketSECAgenticRunner,
        BasketRocketSECRunResult,
        MaterializedSECFiling,
    )
    from .basket_rocket_visualizations import BasketRocketVisualizationResult, generate_basket_rocket_visualizations
    from .democritus_agentic import (
        DemocritusAgenticConfig,
        DemocritusAgenticRunner,
        DemocritusAgentRecord,
        build_democritus_agentic_workflow,
    )
    from .democritus_batch_agentic import DemocritusBatchAgenticRunner, DemocritusBatchConfig, DemocritusBatchRecord
    from .democritus_query_agentic import (
        AcquiredCorpusDocument,
        CrossrefRetrievalBackend,
        DemocritusQueryAgenticConfig,
        DemocritusQueryAgenticRunner,
        DemocritusQueryRunResult,
        DiscoveredDocument,
        QueryPlan,
        SECFilingRetrievalBackend,
        ScholarlyRetrievalBackend,
        SemanticScholarRetrievalBackend,
    )
    from .product_feedback_agentic import (
        ProductFeedbackAgenticConfig,
        ProductFeedbackAgentRecord,
        ProductFeedbackAgenticRunner,
        ProductFeedbackRunResult,
        build_product_feedback_agentic_workflow,
    )
    from .product_feedback_query_agentic import (
        DiscoveredReviewDocument,
        MaterializedReviewDocument,
        ProductFeedbackQueryAgenticConfig,
        ProductFeedbackQueryAgenticRunner,
        ProductFeedbackQueryRunResult,
        ReviewQueryPlan,
    )
    from .product_feedback_visualizations import (
        ProductFeedbackVisualizationResult,
        generate_product_feedback_dashboard,
    )
    from .query_router_agentic import (
        FF2QueryRouter,
        FF2QueryRouterConfig,
        FF2QueryRouterRunResult,
        FF2RouteDecision,
        FF3QueryRouter,
        FF3QueryRouterConfig,
        FF3QueryRouterRunResult,
        FF3RouteDecision,
        route_ff2_query,
        route_ff3_query,
    )
    from .cliff import (
        CLIFFConsciousReturn,
        CLIFFRouteDecision,
        CLIFFRouter,
        CLIFFRouterConfig,
        CLIFFRouterRunResult,
        report_to_cliff_consciousness,
        route_cliff_query,
    )

__all__ = [
    "AgentNode",
    "AgentSpec",
    "AgenticWorkflow",
    "ArtifactNode",
    "ArtifactSpec",
    "AttentionColimit",
    "AttentionScoreWeights",
    "AttentionSpec",
    "BatchCSQLBundleResult",
    "BasketRocketBatchAgenticRunner",
    "BasketRocketBatchRecord",
    "BasketRocketBatchRunResult",
    "BasketRocketSECAgenticConfig",
    "BasketRocketSECAgenticRunner",
    "BasketRocketSECRunResult",
    "BasketRocketVisualizationResult",
    "BroadcastSelection",
    "Category",
    "CLIFFConsciousReturn",
    "CLIFFRouteDecision",
    "CLIFFRouter",
    "CLIFFRouterConfig",
    "CLIFFRouterRunResult",
    "ConsciousBroadcast",
    "ConsciousBroadcastBoard",
    "ConsciousFieldOfView",
    "ConsciousWorkspaceState",
    "ConsciousnessFunctor",
    "DemocritusAgenticConfig",
    "DemocritusAgenticRunner",
    "DemocritusAgentRecord",
    "DemocritusBatchAgenticRunner",
    "DemocritusBatchConfig",
    "DemocritusBatchRecord",
    "DemocritusQueryAgenticConfig",
    "DemocritusQueryAgenticRunner",
    "DemocritusQueryRunResult",
    "DiffusionLimit",
    "DiffusionSpec",
    "DiscoveredDocument",
    "DiscoveredReviewDocument",
    "FF2QueryRouter",
    "FF2QueryRouterConfig",
    "FF2QueryRouterRunResult",
    "FF2RouteDecision",
    "FF3QueryRouter",
    "FF3QueryRouterConfig",
    "FF3QueryRouterRunResult",
    "FF3RouteDecision",
    "Functor",
    "Interface",
    "MaterializedReviewDocument",
    "MaterializedSECFiling",
    "ModelObject",
    "Morphism",
    "ProductFeedbackAgenticConfig",
    "ProductFeedbackAgentRecord",
    "ProductFeedbackAgenticRunner",
    "ProductFeedbackQueryAgenticConfig",
    "ProductFeedbackQueryAgenticRunner",
    "ProductFeedbackQueryRunResult",
    "ProductFeedbackRunResult",
    "ProductFeedbackVisualizationResult",
    "QueryPlan",
    "ReviewQueryPlan",
    "SECFilingRetrievalBackend",
    "ScholarlyRetrievalBackend",
    "SemanticScholarRetrievalBackend",
    "CrossrefRetrievalBackend",
    "AcquiredCorpusDocument",
    "UnconsciousProcess",
    "build_agentic_workflow",
    "build_basket_rocket_workflow",
    "build_democritus_agentic_workflow",
    "build_democritus_workflow",
    "build_product_feedback_agentic_workflow",
    "generate_basket_rocket_visualizations",
    "generate_product_feedback_dashboard",
    "route_ff2_query",
    "route_ff3_query",
    "report_to_cliff_consciousness",
    "route_cliff_query",
]


def __getattr__(name: str):
    if name in {
        "BasketRocketBatchAgenticRunner",
        "BasketRocketBatchRecord",
        "BasketRocketBatchRunResult",
        "BasketRocketSECAgenticConfig",
        "BasketRocketSECAgenticRunner",
        "BasketRocketSECRunResult",
        "BasketRocketVisualizationResult",
        "MaterializedSECFiling",
        "DemocritusBatchAgenticRunner",
        "DemocritusBatchConfig",
        "DemocritusBatchRecord",
        "DemocritusAgenticConfig",
        "DemocritusAgenticRunner",
        "DemocritusAgentRecord",
        "build_democritus_agentic_workflow",
        "DemocritusQueryAgenticConfig",
        "DemocritusQueryAgenticRunner",
        "DemocritusQueryRunResult",
        "DiscoveredDocument",
        "AcquiredCorpusDocument",
        "QueryPlan",
        "CrossrefRetrievalBackend",
        "ScholarlyRetrievalBackend",
        "SemanticScholarRetrievalBackend",
        "SECFilingRetrievalBackend",
        "generate_basket_rocket_visualizations",
        "ProductFeedbackAgenticConfig",
        "ProductFeedbackAgentRecord",
        "ProductFeedbackAgenticRunner",
        "ProductFeedbackRunResult",
        "build_product_feedback_agentic_workflow",
        "DiscoveredReviewDocument",
        "MaterializedReviewDocument",
        "ProductFeedbackQueryAgenticConfig",
        "ProductFeedbackQueryAgenticRunner",
        "ProductFeedbackQueryRunResult",
        "ReviewQueryPlan",
        "ProductFeedbackVisualizationResult",
        "generate_product_feedback_dashboard",
        "FF2QueryRouter",
        "FF2QueryRouterConfig",
        "FF2QueryRouterRunResult",
        "FF2RouteDecision",
        "FF3QueryRouter",
        "FF3QueryRouterConfig",
        "FF3QueryRouterRunResult",
        "FF3RouteDecision",
        "CLIFFConsciousReturn",
        "CLIFFRouteDecision",
        "CLIFFRouter",
        "CLIFFRouterConfig",
        "CLIFFRouterRunResult",
        "route_ff2_query",
        "route_ff3_query",
        "report_to_cliff_consciousness",
        "route_cliff_query",
    }:
        from .basket_rocket_sec_agentic import (
            BasketRocketBatchAgenticRunner,
            BasketRocketBatchRecord,
            BasketRocketBatchRunResult,
            BasketRocketSECAgenticConfig,
            BasketRocketSECAgenticRunner,
            BasketRocketSECRunResult,
            MaterializedSECFiling,
        )
        from .basket_rocket_visualizations import BasketRocketVisualizationResult, generate_basket_rocket_visualizations
        from .democritus_agentic import (
            DemocritusAgenticConfig,
            DemocritusAgenticRunner,
            DemocritusAgentRecord,
            build_democritus_agentic_workflow,
        )
        from .democritus_batch_agentic import (
            DemocritusBatchAgenticRunner,
            DemocritusBatchConfig,
            DemocritusBatchRecord,
        )
        from .democritus_query_agentic import (
            AcquiredCorpusDocument,
            CrossrefRetrievalBackend,
            DemocritusQueryAgenticConfig,
            DemocritusQueryAgenticRunner,
            DemocritusQueryRunResult,
            DiscoveredDocument,
            QueryPlan,
            SECFilingRetrievalBackend,
            ScholarlyRetrievalBackend,
            SemanticScholarRetrievalBackend,
        )
        from .product_feedback_agentic import (
            ProductFeedbackAgenticConfig,
            ProductFeedbackAgentRecord,
            ProductFeedbackAgenticRunner,
            ProductFeedbackRunResult,
            build_product_feedback_agentic_workflow,
        )
        from .product_feedback_query_agentic import (
            DiscoveredReviewDocument,
            MaterializedReviewDocument,
            ProductFeedbackQueryAgenticConfig,
            ProductFeedbackQueryAgenticRunner,
            ProductFeedbackQueryRunResult,
            ReviewQueryPlan,
        )
        from .product_feedback_visualizations import (
            ProductFeedbackVisualizationResult,
            generate_product_feedback_dashboard,
        )
        from .query_router_agentic import (
            FF2QueryRouter,
            FF2QueryRouterConfig,
            FF2QueryRouterRunResult,
            FF2RouteDecision,
            FF3QueryRouter,
            FF3QueryRouterConfig,
            FF3QueryRouterRunResult,
            FF3RouteDecision,
            route_ff2_query,
            route_ff3_query,
        )
        from .cliff import (
            CLIFFConsciousReturn,
            CLIFFRouteDecision,
            CLIFFRouter,
            CLIFFRouterConfig,
            CLIFFRouterRunResult,
            report_to_cliff_consciousness,
            route_cliff_query,
        )

        exported = {
            "BasketRocketBatchAgenticRunner": BasketRocketBatchAgenticRunner,
            "BasketRocketBatchRecord": BasketRocketBatchRecord,
            "BasketRocketBatchRunResult": BasketRocketBatchRunResult,
            "BasketRocketSECAgenticConfig": BasketRocketSECAgenticConfig,
            "BasketRocketSECAgenticRunner": BasketRocketSECAgenticRunner,
            "BasketRocketSECRunResult": BasketRocketSECRunResult,
            "BasketRocketVisualizationResult": BasketRocketVisualizationResult,
            "MaterializedSECFiling": MaterializedSECFiling,
            "DemocritusBatchAgenticRunner": DemocritusBatchAgenticRunner,
            "DemocritusBatchConfig": DemocritusBatchConfig,
            "DemocritusBatchRecord": DemocritusBatchRecord,
            "BatchCSQLBundleResult": BatchCSQLBundleResult,
            "DemocritusAgenticConfig": DemocritusAgenticConfig,
            "DemocritusAgenticRunner": DemocritusAgenticRunner,
            "DemocritusAgentRecord": DemocritusAgentRecord,
            "build_democritus_agentic_workflow": build_democritus_agentic_workflow,
            "DemocritusQueryAgenticConfig": DemocritusQueryAgenticConfig,
            "DemocritusQueryAgenticRunner": DemocritusQueryAgenticRunner,
            "DemocritusQueryRunResult": DemocritusQueryRunResult,
            "DiscoveredDocument": DiscoveredDocument,
            "AcquiredCorpusDocument": AcquiredCorpusDocument,
            "QueryPlan": QueryPlan,
            "CrossrefRetrievalBackend": CrossrefRetrievalBackend,
            "ScholarlyRetrievalBackend": ScholarlyRetrievalBackend,
            "SemanticScholarRetrievalBackend": SemanticScholarRetrievalBackend,
            "SECFilingRetrievalBackend": SECFilingRetrievalBackend,
            "generate_basket_rocket_visualizations": generate_basket_rocket_visualizations,
            "ProductFeedbackAgenticConfig": ProductFeedbackAgenticConfig,
            "ProductFeedbackAgentRecord": ProductFeedbackAgentRecord,
            "ProductFeedbackAgenticRunner": ProductFeedbackAgenticRunner,
            "ProductFeedbackRunResult": ProductFeedbackRunResult,
            "build_product_feedback_agentic_workflow": build_product_feedback_agentic_workflow,
            "DiscoveredReviewDocument": DiscoveredReviewDocument,
            "MaterializedReviewDocument": MaterializedReviewDocument,
            "ProductFeedbackQueryAgenticConfig": ProductFeedbackQueryAgenticConfig,
            "ProductFeedbackQueryAgenticRunner": ProductFeedbackQueryAgenticRunner,
            "ProductFeedbackQueryRunResult": ProductFeedbackQueryRunResult,
            "ReviewQueryPlan": ReviewQueryPlan,
            "ProductFeedbackVisualizationResult": ProductFeedbackVisualizationResult,
            "generate_product_feedback_dashboard": generate_product_feedback_dashboard,
            "FF2QueryRouter": FF2QueryRouter,
            "FF2QueryRouterConfig": FF2QueryRouterConfig,
            "FF2QueryRouterRunResult": FF2QueryRouterRunResult,
            "FF2RouteDecision": FF2RouteDecision,
            "FF3QueryRouter": FF3QueryRouter,
            "FF3QueryRouterConfig": FF3QueryRouterConfig,
            "FF3QueryRouterRunResult": FF3QueryRouterRunResult,
            "FF3RouteDecision": FF3RouteDecision,
            "CLIFFConsciousReturn": CLIFFConsciousReturn,
            "CLIFFRouteDecision": CLIFFRouteDecision,
            "CLIFFRouter": CLIFFRouter,
            "CLIFFRouterConfig": CLIFFRouterConfig,
            "CLIFFRouterRunResult": CLIFFRouterRunResult,
            "route_ff2_query": route_ff2_query,
            "route_ff3_query": route_ff3_query,
            "report_to_cliff_consciousness": report_to_cliff_consciousness,
            "route_cliff_query": route_cliff_query,
        }
        return exported[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
